const { contextBridge, ipcRenderer } = require("electron")

contextBridge.exposeInMainWorld("show0", {
  version: "ui-shell",
  minimizeWindow: () => ipcRenderer.invoke("show0:minimize-window"),
  closeWindow: () => ipcRenderer.invoke("show0:close-window"),
  setWindowResizable: (resizable) => ipcRenderer.invoke("show0:set-window-resizable", Boolean(resizable)),
  setWindowSize: (width, height) => ipcRenderer.invoke("show0:set-window-size", Number(width), Number(height)),
  getAudioDevices: (config) => ipcRenderer.invoke("show0:get-audio-devices", config || {}),
  openDesktopLyrics: () => ipcRenderer.invoke("show0:open-desktop-lyrics"),
  closeDesktopLyrics: () => ipcRenderer.invoke("show0:close-desktop-lyrics"),
  toggleDesktopLyrics: () => ipcRenderer.invoke("show0:toggle-desktop-lyrics"),
  getDesktopLyricsState: () => ipcRenderer.invoke("show0:get-desktop-lyrics-state"),
  setDesktopLyricsLocked: (locked) => ipcRenderer.invoke("show0:set-desktop-lyrics-locked", Boolean(locked)),
  setDesktopLyricsPayload: (payload) => ipcRenderer.invoke("show0:set-desktop-lyrics-payload", payload || {}),
  getDesktopLyricsPayload: () => ipcRenderer.invoke("show0:get-desktop-lyrics-payload"),
  saveRewriteEdit: (songPackageDir, edit) => ipcRenderer.invoke("show0:save-rewrite-edit", String(songPackageDir || ""), edit || {}),
  selectRewriteVocalFile: () => ipcRenderer.invoke("show0:select-rewrite-vocal-file"),
  uploadRewriteVocalFile: (payload) => ipcRenderer.invoke("show0:upload-rewrite-vocal-file", payload || {}),
  enableKugouSync: (config) => ipcRenderer.invoke("show0:kugou-enable", config),
  disableKugouSync: () => ipcRenderer.invoke("show0:kugou-disable"),
  getKugouSyncState: () => ipcRenderer.invoke("show0:kugou-state"),
  kugouSyncEvent: (command) => ipcRenderer.invoke("show0:kugou-sync-event", command),
  shiftKugouLyricOffset: (deltaMs) => ipcRenderer.invoke("show0:kugou-shift-lyric-offset", Number(deltaMs) || 0),
  resetKugouLyricOffset: () => ipcRenderer.invoke("show0:kugou-reset-lyric-offset"),
  selectKugouExePath: () => ipcRenderer.invoke("show0:select-kugou-exe-path"),
  validateKugouExePath: (exePath) => ipcRenderer.invoke("show0:validate-kugou-exe-path", String(exePath || "")),
  autoDetectKugouPaths: () => ipcRenderer.invoke("show0:auto-detect-kugou-paths"),
  selectKugouMusicDir: () => ipcRenderer.invoke("show0:select-kugou-music-dir"),
  selectKugouLyricDir: () => ipcRenderer.invoke("show0:select-kugou-lyric-dir"),
  validateDirectoryPath: (dirPath, emptyReason) => ipcRenderer.invoke("show0:validate-directory-path", String(dirPath || ""), String(emptyReason || "")),
  validateKugouMusicDir: (dirPath) => ipcRenderer.invoke("show0:validate-kugou-music-dir", String(dirPath || "")),
  validateKugouLyricDir: (dirPath) => ipcRenderer.invoke("show0:validate-kugou-lyric-dir", String(dirPath || "")),
  selectShow0RootDir: () => ipcRenderer.invoke("show0:select-show0-root-dir"),
  selectShow0SongDataDir: () => ipcRenderer.invoke("show0:select-show0-song-data-dir"),
  selectShow0SongPackageDir: () => ipcRenderer.invoke("show0:select-show0-song-package-dir"),
  validateShow0RootDir: (dirPath) => ipcRenderer.invoke("show0:validate-show0-root-dir", String(dirPath || "")),
  validateShow0SongDataDir: (dirPath) => ipcRenderer.invoke("show0:validate-show0-song-data-dir", String(dirPath || "")),
  validateShow0SongPackageDir: (dirPath) => ipcRenderer.invoke("show0:validate-show0-song-package-dir", String(dirPath || "")),
  scanShow0SongPackages: (config) => ipcRenderer.invoke("show0:scan-show0-song-packages", config),
  scanShow0Library: (config) => ipcRenderer.invoke("show0:library-scan", { config: config || {} }),
  createCustomPlaylist: (payload) => ipcRenderer.invoke("show0:library-create-playlist", payload || {}),
  renamePlaylist: (payload) => ipcRenderer.invoke("show0:library-rename-playlist", payload || {}),
  deletePlaylist: (payload) => ipcRenderer.invoke("show0:library-delete-playlist", payload || {}),
  moveSongPackagesToPlaylist: (payload) => ipcRenderer.invoke("show0:library-move-to-playlist", payload || {}),
  duplicateSongPackageToDefault: (payload) => ipcRenderer.invoke("show0:library-duplicate-to-default", payload || {}),
  moveSongPackagesToDeleted: (payload) => ipcRenderer.invoke("show0:library-move-to-deleted", payload || {}),
  listDeletedSongPackages: (payload) => ipcRenderer.invoke("show0:library-list-deleted", payload || {}),
  restoreDeletedSongPackages: (payload) => ipcRenderer.invoke("show0:library-restore-deleted", payload || {}),
  permanentlyDeleteSongPackages: (payload) => ipcRenderer.invoke("show0:library-permanently-delete", payload || {}),
  getDeletedRetentionPolicy: (payload) => ipcRenderer.invoke("show0:library-get-retention-policy", payload || {}),
  updateDeletedRetentionPolicy: (payload) => ipcRenderer.invoke("show0:library-update-retention-policy", payload || {}),
  openShow0LibraryFolder: (payload) => ipcRenderer.invoke("show0:library-open-folder", payload || {}),
  saveKugouSyncConfig: (config) => ipcRenderer.invoke("show0:save-kugou-sync-config", config),
  getKugouSyncConfig: () => ipcRenderer.invoke("show0:get-kugou-sync-config"),
  getSongShow0Config: (songPackageDir) => ipcRenderer.invoke("show0:get-song-show0-config", String(songPackageDir || "")),
  updateSongShow0Parameters: (songPackageDir, parametersPatch) => ipcRenderer.invoke("show0:update-song-show0-parameters", String(songPackageDir || ""), parametersPatch || {}),
  readSongPackageManifest: (songPackageDir) => ipcRenderer.invoke("show0:read-song-package-manifest", String(songPackageDir || "")),
  resolveSongCover: (songPackageDir) => ipcRenderer.invoke("show0:resolve-song-cover", String(songPackageDir || "")),
  getGateControlState: () => ipcRenderer.invoke("show0:get-gate-control-state"),
  setGateControlState: (payload) => ipcRenderer.invoke("show0:set-gate-control-state", payload || {}),
  getGatePluginStatus: () => ipcRenderer.invoke("show0:get-gate-plugin-status"),
  songPackageFileExists: (songPackageDir, relativePath) => ipcRenderer.invoke("show0:song-package-file-exists", String(songPackageDir || ""), String(relativePath || "")),
  readSongPackageJsonResource: (songPackageDir, relativePath) => ipcRenderer.invoke("show0:read-song-package-json-resource", String(songPackageDir || ""), String(relativePath || "")),
  resolvePlaybackAudio: (songPackageDir) => ipcRenderer.invoke("show0:resolve-playback-audio", String(songPackageDir || "")),
  getAudioCoreCapabilities: () => ipcRenderer.invoke("show0:get-audio-core-capabilities"),
  resolveAudioCoreTracks: (songPackageDir) => ipcRenderer.invoke("show0:resolve-audio-core-tracks", String(songPackageDir || "")),
  nativeAudioCore: (command, payload) => ipcRenderer.invoke("show0:native-audio-core", String(command || ""), payload || {}),
  readShow0Lyrics: (songPackageDir, rewriteMode) => ipcRenderer.invoke("show0:read-show0-lyrics", String(songPackageDir || ""), Boolean(rewriteMode)),
  importKugouKrcLyrics: (payload) => ipcRenderer.invoke("show0:import-kugou-krc-lyrics", payload || {}),
  createSongPackageFromImports: (payload) => ipcRenderer.invoke("show0:create-song-package-from-imports", payload || {}),
  getAppRuntimeInfo: () => ipcRenderer.invoke("show0:get-app-runtime-info"),
  scanDataMigrationCurrent: (payload) => ipcRenderer.invoke("show0:scan-data-migration-current", payload || {}),
  validateDataMigrationTarget: (payload) => ipcRenderer.invoke("show0:validate-data-migration-target", payload || {}),
  startDataMigration: (payload) => ipcRenderer.invoke("show0:start-data-migration", payload || {}),
  openDirectoryIfExists: (dirPath) => ipcRenderer.invoke("show0:open-directory-if-exists", String(dirPath || "")),
  updateSongPackage: (payload) => ipcRenderer.invoke("show0:update-song-package", payload || {}),
  readSongWaveforms: (songPackageDir) => ipcRenderer.invoke("show0:read-song-waveforms", String(songPackageDir || "")),
  moveSongPackageToTempTrash: (songPackageDir) => ipcRenderer.invoke("show0:move-song-package-to-temp-trash", String(songPackageDir || "")),
  clearTempSongPackageTrash: () => ipcRenderer.invoke("show0:clear-temp-song-package-trash"),
  onDesktopLyricsPayload: (callback) => {
    const listener = (_event, payload) => callback(payload)
    ipcRenderer.on("show0:desktop-lyrics-payload", listener)
    return () => ipcRenderer.removeListener("show0:desktop-lyrics-payload", listener)
  },
  onDesktopLyricsState: (callback) => {
    const listener = (_event, state) => callback(Boolean(state && state.open))
    ipcRenderer.on("show0:desktop-lyrics-state", listener)
    return () => ipcRenderer.removeListener("show0:desktop-lyrics-state", listener)
  },
  onDataMigrationProgress: (callback) => {
    const listener = (_event, payload) => callback(payload)
    ipcRenderer.on("show0:data-migration-progress", listener)
    return () => ipcRenderer.removeListener("show0:data-migration-progress", listener)
  },
})
